version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.13
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: npm-{{ checksum "package.json" }}
      - run: yarn build
    docker:
      - image: circleci/node:10.13
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: npm-{{ checksum "package.json" }}
      - run: yarn lint
  test:e2e:
    docker:
      - image: circleci/node:10.13
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: npm-{{ checksum "package.json" }}
      - run: yarn test:e2e
test:unit:
  docker:
    - image: circleci/node:10.13
  steps:
    - checkout
    - restore_cache:
        keys:
          - npm-{{ checksum "package.json" }}
    - run: yarn install
    - save_cache:
        paths:
          - node_modules
        key: npm-{{ checksum "package.json" }}
    - run: yarn test:unit
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - linter
      # - test:unit
      # - test:e2e