version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.13
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: npm-{{ checksum "package.json" }}
      - run: yarn lint
      - run: yarn test
  linter:
    docker:
      - image: circleci/node:10.13
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: npm-{{ checksum "package.json" }}
      - run: yarn lint
  test:
    docker:
      - image: circleci/node:10.13
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: npm-{{ checksum "package.json" }}
      - run: yarn test

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - linter
      - test 